# Generated by Django 5.1.4 on 2024-12-23 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_full_name_alter_customuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_reset_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
