# Generated by Django 5.1.4 on 2024-12-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionplan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='dedicated_proxies',
            field=models.BooleanField(default=False, help_text='Access to dedicated proxy pools'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='premium_templates',
            field=models.BooleanField(default=False, help_text='Access to premium templates'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.IntegerField(default=0, help_text='Number of trial days (0 for no trial)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='api_limit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='concurrent_scrapes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
