# Generated by Django 5.1.4 on 2024-12-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionplan', '0002_remove_subscriptionplan_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='data_limit',
            field=models.FloatField(default=100.0, help_text='Data volume limit (in MB).'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price for the plan.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='duration',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Monthly', help_text='Subscription duration.', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priority for sorting plans.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='api_limit',
            field=models.IntegerField(help_text='Maximum API calls allowed per month.'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='concurrent_scrapes',
            field=models.IntegerField(default=1, help_text='Number of concurrent scraping tasks allowed.'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='dedicated_proxies',
            field=models.BooleanField(default=False, help_text='Access to dedicated proxy pools.'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='premium_templates',
            field=models.BooleanField(default=False, help_text='Access to premium templates.'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.IntegerField(default=0, help_text='Number of trial days (0 for no trial).'),
        ),
    ]
