# Generated by Django 5.1.4 on 2024-12-22 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxypool', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProxyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('proxies', models.ManyToManyField(related_name='assigned_users', to='proxypool.proxypool')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_assignment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
